### ISSUE TITLE
PortableApps Platform Compatability Issue

### ISSUE THREAD

**Issue by ehcorn** [Numstr/Obsidian-Portable#1]
I'm not sure if this is something that changing the app would help, but when I move the obsidian portable folder into the portable apps launcher folder obsidian shows up properly, but when I get the following error:

---------------------------
PortableApps.com Platform
---------------------------
Could not find: E:\PortableApps\ObsidianPortable\[PAF Error - Missing Start].
---------------------------
OK   
---------------------------

what's also interesting is that when I hover over the obsidian icon in the launcher it shows not the obsidianportable.exe file that it should be picking, but that it's trying to run "E:\PortableApps\ObsidianPortable\[PAF Error - Missing Start" as the main executable. Renaming hasn't helped, nor has editing the PortableApps ini file to force it to pick the right exe.

**Comment by matthewsheeran** [comment]
Yeah it's a bug: something must have changed with later PortableApp releases.

Funnily enough - at least after running Update.bat - and after turning off read-only for all files before that - you can at least double-click the Obsidian-Portable.exe app from within Explorer and it actually runs.

So I went and installed the vanilla Obsidian which installs without Admin per User anyways for now..

**Comment by Numstr** [comment]
> #### Could not find: E:\PortableApps\ObsidianPortable[PAF Error - Missing Start].

Add this to "ObsidianPortable\App\AppInfo\AppInfo.ini"
```
[Control]
Start=ObsidianPortable.exe
```
Also you can add category to [Details]
(Accessibility, Development, Office etc)
```
Category=Office
```

**Comment by ehcorn** [comment]
> > #### Could not find: E:\PortableApps\ObsidianPortable[PAF Error - Missing Start].
> 
> Add this to "ObsidianPortable\App\AppInfo\AppInfo.ini"
> 
> ```
> [Control]
> Start=ObsidianPortable.exe
> ```
> 
> Also you can add category to [Details] (Accessibility, Development, Office etc)
> 
> ```
> Category=Office
> ```

Confirmed this fixed the issue. I'm even testing this on a veracrypt volume for a fully-encrypted local notes packages, with syncthing plugged into the whole thing and it's perfect for an untrusted system!

**Comment by clutterwhy** [comment]
What version is this obsidian
