### ISSUE TITLE
Error with Updator.bat

### ISSUE THREAD

**Issue by baskgithub** [Numstr/Obsidian-Portable#4]
When running the Updator.bat, I got following errors. 
This is the first time I use this tool, I wonder how to fix this...

Thank you!

```txt
E:\ObsidianPortable> updater.bat
No Instance(s) Available.
Current:
Latest: 1.7.4

Connecting to 127.0.0.1:3128 ((null))
saving to 'TMP\Obsidian-1.7.4.exe'
Obsidian-1.7.4.exe   100% |************************************************************************|  4344  0:00:00 ETA
'TMP\Obsidian-1.7.4.exe' saved

Unpacking
ERROR: TMP\Obsidian-1.7.4.exe
Cannot open the file as archive


ERROR: The system cannot find the file specified.
TMP\4.7z



System ERROR:
The system cannot find the file specified.

Done
Press any key to continue . . .
```

**Comment by Numstr** [comment]
There is something wrong with your connection. As you can see the script is trying to connect localhost (127.0.0.1:3128) not to github, maybe something is blocking wget connection to github.
```
Latest: 1.7.4

Connecting to github.com (140.82.121.4:443)
Connecting to objects.githubusercontent.com (185.199.108.133:443)
saving to 'TMP\Obsidian-1.7.4.exe'
Obsidian-1.7.4.exe   100% |************************************************************************|  239M  0:00:00 ETA
'TMP\Obsidian-1.7.4.exe' saved
```

**Comment by baskgithub** [comment]
Thank you.

I'm using a proxy server (px) listening at 127.0.0.1:3128.

I am wondering whether there is a way to make it portable after download the obsidian installer manully.

**Comment by Numstr** [comment]
Sure, check this: https://github.com/Numstr/Obsidian-Portable/issues/2#issuecomment-2194767265

Or you can use CMD

Put installer to ObsidianPortable root and open CMD here.
for x32
`.\App\Utils\7za.exe x -t# -aoa Obsidian-1.7.4.exe -o"TMP" 6.7z`
`.\App\Utils\7za.exe x -aoa TMP\6.7z -o"App\Obsidian" & rmdir "TMP" /s /q`
for x64
`.\App\Utils\7za.exe x -t# -aoa Obsidian-1.7.4.exe -o"TMP" 4.7z`
`.\App\Utils\7za.exe x -aoa TMP\4.7z -o"App\Obsidian" & rmdir "TMP" /s /q`

**Comment by baskgithub** [comment]
thanks for teaching me, it works!
